[project]
name = "cursor-ai"
version = "0.1.0"
description = "Interactive AI code generator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai",
    "opencv-python",
    "matplotlib",
    "numpy"
]

[project.scripts]
cursor-ai = "cursor_ai.cli:start_cli"
